spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mileage?useSSL=false
    username: root
    password: tiger


mybatis:
  type-aliases-package: com.example.reviewmileage.infrastructures.model
